### ISSUE TITLE
Compiled on PHP7 but don't working

### ISSUE THREAD

**Issue by ointeractive-depot** [RDashINC/embeder2#3]
Hello! I've spent two days (but not whole of them) to compile it with PHP7 and it's done without any errors and warnings finally. It was required for me to make some changes at make_embeder.bat, update the project with VC 2015, build it strongly on x86 platform (but it's more better than build it at x64 directly), and finish it with other PHP with win32std.dll (I don't understand why, but it couldn't start at my PHP compiled with it, so I've decided to add it at my fighting server in php.ini as extension and started it with it).

But I have a big problem: when I've started it, I've got a message that php5ts.dll is missing, so I've copied it manually (really?) from my working server and renamed it to php7ts.dll, but now it's crashes after its start. I've tried to find the text like "php5", "php5ts" at all project files, but find nothing. I've changed the dependencies from php5embed.lib and php5ts.lib to php7embed.lib and php7ts.lib at project etc, but I can't find another php5* and have no any thoughts why it's refused to work, so I really need your help, because it's the best feeling to give the second life to something ancient.

Thanks in advance!

**Comment by jaredallard** [comment]
I'll throw up a Windows VM and check it out. I know I got this working though. 🤔

If I don't have a solution by the 6th -- ping me.

**Comment by jaredallard** [comment]
It does sound like a case of some sort of mismatching in the compilation, but I can't be sure.

**Comment by jaredallard** [comment]
You did compile on php7 branch, right? Sorry mobile doesn't do edits.

**Comment by ointeractive-depot** [comment]
Ah, okay, don't worry) There's no rush for me if you have a night.
Yes, php7, right you.

And my thougts is that it waiting for some content of php5ts.dll from PHP5, but can't find it because PHP7 is differ so much I think. Some kind of theory too)

**Comment by ointeractive-depot** [comment]
Oh myyyyy! It seems that I've worked with the master branch! But I've simply downloaded it in archive on my PC, I thought it's actually ever. Why it has occurred, do you know? Don't you forget to make it public? I think it'll be nice to make it master.

Thanks for advice so much, I'll surely check it with other branch.

**Comment by ointeractive-depot** [comment]
All right, compile php7 branch correctly (but it's strange that master branch version for PHP5< compiled on PHP7 without errors, but anything terrible I think), but now I get a errors after embeder2.exe starts:

```
Warning: include(): Unable to find the wrapper "res" - did you forget to enable it when you configured PHP? in main on line 1

Warning: include(): Unable to find the wrapper "res" - did you forget to enable it when you configured PHP? in main on line 1

Warning: include(res:///PHP/LIB): failed to open stream: No such file or directory in main on line 1

Warning: include(): Failed opening 'res:///PHP/LIB' for inclusion (include_path='.;C:\php\pear') in main on line 1
```
It seems that it's starts on a PHP compiled without `--enable-embed` key, but it is working correctly when it build via make_embeder.cmd and wrote to this wrapper successfully:

```
'.\embeder2.exe' created
Updated 'res://.\embeder2.exe/PHP/RUN/1036' with 5943 bytes
Updated 'res://.\embeder2.exe/PHP/54a17e0796234b90551e35f245e5409e' with 18944 bytes
Done
```

Seems that compile action and load action uses different PHP's but why and where?

**Comment by ointeractive-depot** [comment]
Solved this problem with adding the _php_win32std.dll_ to the _ext_ folder and specifying it in _php.ini_. But I thougth there's a way to make an autonomical files which is not requires any other files at all. And I added it at _php.ini_ file and it's working, not at _php-embed.ini_. I find it's so strange and think that it's not healthy... Yes...
